package bestiariomonsterhunter.Monstruos;

import bestiariomonsterhunter.VentanaPrincipal;

/**
 *
 * @author Víctor Arroyo
 */
public class InformaciónMonstruoGUI extends javax.swing.JFrame {

    /**
     * Creates new form InformaciónMonstruoGUI
     */
    VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();

    public InformaciónMonstruoGUI() {
        initComponents();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {

                ventanaPrincipal.setLocationRelativeTo(null);
                ventanaPrincipal.setVisible(true);
                ventanaPrincipal.switchView();
                ventanaPrincipal.actualizarTablaFiltradaTipoMonstruo();
            }
        });
        labelDescripcion.setEditable(false);
        labelDescripcion.setLineWrap(true);
        labelDescripcion.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelImgMonstruo = new javax.swing.JLabel();
        labelDebilidad = new javax.swing.JLabel();
        labelElemento = new javax.swing.JLabel();
        labelNombreMonstruo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información del monstruo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBackground.setBackground(new java.awt.Color(102, 102, 102));

        labelImgMonstruo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestiariomonsterhunter/img/monstruos/rathian.png"))); // NOI18N

        labelDebilidad.setBackground(new java.awt.Color(0, 0, 0));
        labelDebilidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelDebilidad.setForeground(new java.awt.Color(255, 255, 255));
        labelDebilidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestiariomonsterhunter/img/elementos/electrico.png"))); // NOI18N
        labelDebilidad.setText("Debilidad");
        labelDebilidad.setOpaque(true);

        labelElemento.setBackground(new java.awt.Color(0, 0, 0));
        labelElemento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelElemento.setForeground(new java.awt.Color(255, 255, 255));
        labelElemento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bestiariomonsterhunter/img/elementos/fisico.png"))); // NOI18N
        labelElemento.setText("Elemento");
        labelElemento.setOpaque(true);

        labelNombreMonstruo.setBackground(new java.awt.Color(51, 51, 51));
        labelNombreMonstruo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelNombreMonstruo.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreMonstruo.setText("NOMBRE DE MONSTRUO");
        labelNombreMonstruo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        labelNombreMonstruo.setOpaque(true);

        labelDescripcion.setBackground(new java.awt.Color(51, 51, 51));
        labelDescripcion.setColumns(1);
        labelDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        labelDescripcion.setRows(10);
        labelDescripcion.setText("Descipción");
        labelDescripcion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        labelDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelNombreMonstruo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                            .addComponent(labelElemento)
                            .addGap(11, 11, 11)
                            .addComponent(labelDebilidad))
                        .addComponent(labelImgMonstruo)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelNombreMonstruo)
                .addGap(18, 18, 18)
                .addComponent(labelImgMonstruo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelElemento)
                    .addComponent(labelDebilidad))
                .addGap(30, 30, 30)
                .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        getContentPane().add(panelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformaciónMonstruoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformaciónMonstruoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformaciónMonstruoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformaciónMonstruoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformaciónMonstruoGUI().setVisible(true);
            }
        });
    }
    
    public void setDatosMonstruo(Monstruo m) {
        labelNombreMonstruo.setText(m.getNombre());
        labelImgMonstruo.setIcon(m.getImagen());
        labelElemento.setIcon(m.getIconoElemento());
        labelDebilidad.setIcon(m.getIconoDebilidad());
        labelDescripcion.setText(m.getDescripcion());
        
        if (ventanaPrincipal.isListaFiltrada()) {
            if (m instanceof Volador) {
                ventanaPrincipal.setTipoMonstruo("volador");
            } else if (m instanceof Terrestre) {
                ventanaPrincipal.setTipoMonstruo("terrestre");
            } else if (m instanceof Acuatico) {
                ventanaPrincipal.setTipoMonstruo("acuatico");
            } else if (m instanceof DragonAnciano) {
                ventanaPrincipal.setTipoMonstruo("anciano");
            }
        } else{
            ventanaPrincipal.setTipoMonstruo("todos");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDebilidad;
    private javax.swing.JTextArea labelDescripcion;
    private javax.swing.JLabel labelElemento;
    private javax.swing.JLabel labelImgMonstruo;
    private javax.swing.JLabel labelNombreMonstruo;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables
}
